version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/wd
    steps:
      # if markdown includes characters other than ascii (e.g. Japanese) you needs to install fonts like below
      # - run: sudo apt-get update && sudo apt-get install fonts-ipaexfont -y
      - checkout
      - restore_cache:
          keys:
            - gdrive-v2.1.0
            - npm-{{ checksum "package.json" }}
      - run: |
          if [ ! -f gdrive ] ; then
            wget "https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64" -O gdrive
            [ `sha1sum gdrive | awk '{print $1}'` = '6ef7c740e980358a9a5de36c1aac7ea375319aa3' ]
            chmod +x gdrive
          fi
      - save_cache:
          key: gdrive-v2.1.0
          paths:
            - ~/wd/gdrive
      - run: npm i
      - save_cache:
          key: npm-{{ checksum "package.json" }}
          paths:
            - ~/wd/node_modules
      - run: npm run build
      - deploy:
          command: |
            echo $GOOGLE_SERVICE_ACCOUNT_CREDENTIAL > credential.json
            dirname=`date +%Y%m%d_%H%M%S` && mv build $dirname
            ./gdrive upload --config `pwd` --service-account credential.json --parent {parent_folder_id_here} --recursive $dirname
